version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-leave
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: leave_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5202:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      leave-network: {}

  backend:
    build: ./Backend
    container_name: backend-leave
    ports:
      - "3202:3202"
    depends_on:
      - postgres
    networks:
      leave-network: {}

  employee-leave:
    build: ./employee-leave
    container_name: employee-leave-ui
    ports:
      - "8004:80"
    depends_on:
      - backend
    networks:
      leave-network: {}

  hr-leave:
    build: ./hr-leave
    container_name: hr-leave-ui
    ports:

      - "8005:80"

    depends_on:
      - backend
    networks:
      leave-network: {}

volumes:
  pgdata:

networks:
  leave-network: {}

