version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: leave_postgres
    environment:
      POSTGRES_DB: leave_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5202:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: leave_backend
    ports:
      - "3202:3202"
    depends_on:
      - postgres

  employee-leave:
    build: ./Employee-leave
    container_name: leave_employee
    ports:
      - "8004:80"
    depends_on:
      - backend

  hr-leave:
    build: ./HR-leave
    container_name: leave_hr
    ports:
      - "8005:80"
    depends_on:
      - backend

volumes:
  pgdata:

